### ISSUE TITLE
Issue exporting

### ISSUE THREAD

**Issue by MerrillL** [rpav/io_scene_consmodel#1]
I know this is old but i tried using this on both 2.79 and 2.71 and got the same error message when exporting
[https://media.discordapp.net/attachments/185590907947581440/442177869670776852/unknown.png](url)

I know you've probably moved onto other things by now but any help with this would be greatly appreciated

**Comment by rpav** [comment]
Sorry, I should probably tag this and a few other things as "deprecated" ... I'm not entirely sure why it wouldn't be loading and I haven't really touched it in awhile.

It's probably not worth using or developing this over something like [glTF](https://www.khronos.org/gltf/) which has [an official Blender exporter](https://github.com/KhronosGroup/glTF-Blender-Exporter) (and an [unofficial one](https://github.com/Kupoman/blendergltf)?) that do a lot more already.
